//
// Created by angely on 8/21/26.
//

#ifndef SYSTEM_IMAGE_VIEWER_NATIVECONTEXTMENU_H
#define SYSTEM_IMAGE_VIEWER_NATIVECONTEXTMENU_H


class NativeContextMenu {
};


#endif //SYSTEM_IMAGE_VIEWER_NATIVECONTEXTMENU_H
